name: Image Scan ðŸ•·ï¸

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

env:
  BUILDAH_FORMAT: "docker"
  #IMAGE_TAG: ${{ github.sha }}
  REGISTRY: docker.io
  REPOSITORY: docker.io/containerscrew/infratools

jobs:
  build:
    name: Scan image
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Get latest image tag to scan
        id: set_tag
        run: |
          # Get latest tag
          LATEST_TAG=$(curl -s https://api.github.com/repos/containerscrew/infratools/tags | jq -r '.[0].name')
          echo "LATEST_TAG=$LATEST_TAG" >> "$GITHUB_ENV"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/containerscrew/infratools:v1.4.1'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'